.TH PDFARRANGER 1 "May 2019" "version 1.2" "User Manuals"
.SH "NAME"
PDF Arranger \- Application for PDF Merging, Rearranging, Splitting, and Cropping
.SH "SYNOPSIS"
.B pdfarranger [file1] [file2] ...
.SH "DESCRIPTION"
.B PDF Arranger
is a small python-gtk application, which helps
the user to merge or split pdf documents and rearrange their
pages using an interactive and intuitive graphical interface.
In the current version, page rotation and cropping is also
supported. PDF Arranger is a frontend for pikepdf.
.SH "OPTIONS"
Currently PDF Arranger doesn't receive any options.
.SH "FILES"
$HOME/.config/pdfarranger/config.ini
.SH "ENVIRONMENT"
All gtk related environment variables.
.SH "DIAGNOSTICS"
Common python and gtk diagnostics.
.SH "AUTHOR"
Konstantinos Poulios <logari81@gmail.com>, Jerome Robert <jeromerobert@gmx.com>
.SH COPYRIGHT
Copyright \(co 2008-2017 Konstantinos Poulios, 2018-2019 Jerome Robert
.br
.SH LICENSE
GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
