.TH PDFSHUFFLER 1 "October 2014" "version 0.7" "User Manuals"
.SH "NAME"
PDF-Shuffler \- Application for PDF Merging, Rearranging, and Splitting
.SH "SYNOPSIS"
.B pdfshuffler [file1] [file2] ...
.SH "DESCRIPTION"
.B PDF-Shuffler
is a small python-gtk application, which helps
the user to merge or split pdf documents and rearrange their
pages using an interactive and intuitive graphical interface.
In the current version, page rotation and cropping is also
supported. PDF-Shuffler is a frontend for python-pyPdf.
.SH "OPTIONS"
Currently PDF-Shuffler doesn't receive any options.
.SH "FILES"
Currently PDF-Shuffler has no configuration file.
.SH "ENVIRONMENT"
All gtk related enviroment variables.
.SH "DIAGNOSTICS"
Common python and gtk diagnostics.
.SH "AUTHOR"
Konstantinos Poulios <logari81@gmail.com>

